
services:

  frontend:
    container_name: ict381app
    image: ict381_staycation
    build: .
    networks:
      - ict381network
    ports:
      - "5000:5000"

  db:
    container_name: ict381db
    image: ict381_mongo
    build:
      context: .
      dockerfile: DockerfileMongo
    networks:
      - ict381network
    ports:
      - "27017:27017"

  nginx:
    container_name: ict381reactWeb
    image: ict381_nginx_react
    build: 
      context: .
      dockerfile: DockerfileReact
    networks:
      - ict381network
    ports:
      - "80:80"
    depends_on:
      - frontend

networks:
  ict381network:
  
